# Generated by Django 4.1.4 on 2022-12-12 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehiculos', '0007_vehiculos_precio_alter_ubicacion_codigopostal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacen',
            options={'permissions': [('admin_almacen_generic', 'Puede Editar y Crear Vehiculos')]},
        ),
        migrations.AlterModelOptions(
            name='entregas',
            options={'permissions': [('admin_entregas_generic', 'Puede Editar y Crear Vehiculos')]},
        ),
        migrations.AlterModelOptions(
            name='vehiculos',
            options={'permissions': [('admin_generic', 'Puede Editar y Crear Vehiculos'), ('suscriptor', 'Solo mostrara el detalle')]},
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='portada',
            field=models.ImageField(blank=True, upload_to='portada/'),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='Disponible',
            field=models.CharField(max_length=2),
        ),
        migrations.CreateModel(
            name='Comentarioentregas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=200)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entregas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_entregas', to='vehiculos.entregas')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarioalmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=200)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_almacen', to='vehiculos.almacen')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
